# Generated by Django 4.1 on 2022-09-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='tasks',
        ),
    ]
