# Generated by Django 4.1 on 2022-09-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_room_members_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='request_string',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('a', 'Accepted'), ('r', 'Rejected')], max_length=1),
        ),
    ]
