# Generated by Django 4.1 on 2022-09-05 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_room_request_string_alter_joinrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='request_string',
        ),
    ]
