# Generated by Django 4.1 on 2022-09-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_remove_room_request_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='request_string',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
