# Generated by Django 4.1 on 2022-09-07 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0008_alter_room_leader_alter_room_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms_own', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='user_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
