# Generated by Django 4.1 on 2022-09-07 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0009_alter_room_leader_alter_room_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('p', 'Pending'), ('a', 'Accepted'), ('r', 'Rejected')], default='p', max_length=1)),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invitation', to=settings.AUTH_USER_MODEL)),
                ('from_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_invitation', to='room.room')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
