# Generated by Django 4.1.3 on 2022-12-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviterequest',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'REJECTED')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'REJECTED')], default='P', max_length=1),
        ),
    ]
