# Generated by Django 4.1 on 2022-09-04 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('done', models.BooleanField(default=False)),
                ('difficulty', models.CharField(choices=[('e', 'Easy'), ('el', 'Elementary'), ('m', 'Medium'), ('h', 'Hard')], max_length=2)),
                ('status', models.CharField(choices=[('d', 'Done'), ('dg', 'Doing'), ('s', 'Stuck'), ('t', 'Testing')], max_length=2)),
                ('priority', models.CharField(choices=[('l', 'Low'), ('me', 'Medium'), ('ma', 'Major'), ('sh', 'Showstopper')], max_length=2)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
