# Generated by Django 4.1 on 2022-09-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('a', 'Assigning'), ('d', 'Done'), ('dg', 'Doing'), ('s', 'Stuck'), ('t', 'Testing')], max_length=2),
        ),
    ]
