# Generated by Django 4.1 on 2022-10-06 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_alter_room_id'),
        ('task', '0005_task_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('a', 'Assigning'), ('d', 'Done'), ('dg', 'Doing'), ('s', 'Stuck'), ('t', 'Testing')], default='a', max_length=2),
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_phases', to='room.room')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phase_tasks', to='task.phase'),
        ),
    ]
