# Generated by Django 4.1.3 on 2022-12-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_phase_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.CharField(choices=[('E', 'Easy'), ('EL', 'Elementary'), ('M', 'Medium'), ('H', 'Hard')], max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('ME', 'Medium'), ('MA', 'Major'), ('SH', 'Showstopper')], max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('A', 'Assigning'), ('D', 'Done'), ('DG', 'Doing'), ('S', 'Stuck'), ('T', 'Testing')], default='a', max_length=2),
        ),
    ]
